### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by ghost** [roys/java-android-developertools#1]
Hi, load this app on F-Droid, please!

**Comment by pjacket** [comment]
#1

**Comment by Systemreiniger092016** [comment]
Ghost,
Hi, 'load this app on F-Droid, please'!
Your comment 2 years ago.
I have an simple answer ....
Why ?
This questions is only for different way of my understand what i've tried is the first got here in your comment. I am in Orientation for learning more about Android make devices possible and easier like on third parties way for consumers with small budget or a cup of coffee.


Thank you very much ... ghost.

This Issue was operating by speaking on Google Mail voice app.

Mike Kuppler
